### ISSUE TITLE
Recurring errors 

### ISSUE THREAD

**Issue by Gravy59** [TomDotBat/pixel-hud#2]
I put this on a test server and it gave me two errors updating each frame
```
[pixel-hud] addons/pixel-hud/lua/pixelhud/common/cl_player_vars.lua:29: attempt to call local 'getter' (a nil value)
  1. checkChanges - addons/pixel-hud/lua/pixelhud/common/cl_player_vars.lua:29
   2. fn - addons/pixel-hud/lua/pixelhud/common/cl_player_vars.lua:94
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109 (x1328)
```
It doesn't conflict with ulib because I removed it and it gave me the same error. I hate to just drop an error on you but I have no idea what's wrong.

**Comment by TomDotBat** [comment]
Try removing this line and see if that fixes your issue:
https://github.com/TomDotBat/pixel-hud/blob/d59c8b48955aed6ebc66aa65f13aad671496f54c/lua/pixelhud/common/cl_player_vars.lua#L94

**Comment by Gravy59** [comment]
Sorry for taking so long to reply. That fixed it completely!
